name: Build NAStool Windows
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - version.py
      - .github/workflows/build-windows.yml

env:
  PYTHON_VERSION: "3.14.2"
  PYTHON_HOME: C:\hostedtoolcache\windows\Python\3.14.2\x64

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
    - name: init Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: install dependent packages
      run: |
        python -m pip install --upgrade pip
        pip install wheel numpy pyparsing wxpython pyinstaller
        git clone --depth=1 -b main https://github.com/Coolkids/nas-tools --recurse-submodule
        cd nas-tools
        python -m pip install -r requirements.txt
        echo ("NASTOOL_CONFIG=D:/a/nas-tools/nas-tools/nas-tools/config/config.yaml") >> $env:GITHUB_ENV
        echo $env:NASTOOL_CONFIG
      shell: pwsh
    - name: package through pyinstaller
      run: |
        cd nas-tools
        copy .\windows\rely\upx.exe $env:PYTHON_HOME\Scripts
        copy .\windows\rely\hook-cn2an.py $env:PYTHON_HOME\lib\site-packages\pyinstaller\hooks
        copy .\windows\rely\hook-zhconv.py $env:PYTHON_HOME\lib\site-packages\pyinstaller\hooks
        copy .\third_party.txt .\windows
        copy .\windows\rely\template.jinja2 $env:PYTHON_HOME\lib\site-packages\pyparsing\diagram
        xcopy .\web $env:PYTHON_HOME\lib\site-packages\web\ /e
        xcopy .\config $env:PYTHON_HOME\lib\site-packages\config\ /e
        xcopy .\db_scripts $env:PYTHON_HOME\lib\site-packages\db_scripts\ /e
        cd windows
        pyinstaller nas-tools.spec
      shell: pwsh
    - name: upload windows file
      uses: actions/upload-artifact@v4
      with:
        name: windows
        path: D:/a/nas-tools/nas-tools/nas-tools/windows/dist/nas-tools.exe

  Create-release_Send-message:
    runs-on: ubuntu-latest
    needs: [windows-build]
    steps:
    - uses: actions/checkout@v4
    - name: Release version
      id: release_version
      run: |
        app_version=$(cat version.py |sed -ne "s/APP_VERSION\s=\s'v\(.*\)'/\1/gp")
        echo "app_version=$app_version" >> $GITHUB_ENV
    - name: download exe and rename
      uses: actions/download-artifact@v4
    - name: get release_informations
      shell: bash
      run: |
        pwd
        mkdir releases
        cd windows
        mv nas-tools.exe /home/runner/work/nas-tools/nas-tools/releases/nastool_win_v${{ env.app_version }}.exe
        dir
        pwd
    - name: Create release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.UPLOAD_KEY }}
      with:
        tag_name: v${{ env.app_version }}
        release_name: v${{ env.app_version }}
        body: ${{ github.event.commits[0].message }}
        draft: false
        prerelease: false
    - name: Upload release asset
      uses: dwenegar/upload-release-assets@v1
      env:
        GITHUB_TOKEN: ${{ secrets.UPLOAD_KEY }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
        assets_path: |
            /home/runner/work/nas-tools/nas-tools/releases/
